services:
  app:
    build: .
    image: state-voterfiles
    container_name: abstract-data-state-voterfiles
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    volumes:
      - ~/PyCharmProjects/state-voterfiles/voter_files:/app/voter_files