[SETTINGS]
FIELD-FORMATTING.date = "%m/%d/%Y"
FILE-ENCODING.type = "null"
VOTER-ID.min-length = "null"
VOTER-ID.max-length = "null"
STATE.abbreviation = "PA"

# ENUMERATED HEADERS
[HEADERS]
    1 = "ID Number"  # SURE Voter ID number
    2 = "Title"
    3 = "Last Name"
    4 = "First Name"
    5 = "Middle Name"
    6 = "Suffix"
    7 = "Gender"
    8 = "DOB"
    9 = "Registration Date"
    10 = "Voter Status"
    11 = "Status Change Date"
    12 = "Party Code"  # Political Party code documentation
    13 = "House Number Residential"
    14 = "House Number Suffix Residential"
    15 = "Street Name Residential"
    16 = "Apartment Number Residential"
    17 = "Address Line 2 Residential"
    18 = "City Residential"
    19 = "State Residential"
    20 = "Zip Residential"
    21 = "Mail Address 1"
    22 = "Mail Address 2"
    23 = "Mail City"
    24 = "Mail State"
    25 = "Mail Zip"
    26 = "Last Vote Date"
    27 = "Precinct Code"
    28 = "Precinct Split ID"
    29 = "Date Last Changed Date"
    30 = "Custom Data 1"  # Legacy system ID number
    31 = "District 1"   #See Zone Code and Zone Type documentation for District 1 to District 40
    32 = "District 2"
    33 = "District 3"
    34 = "District 4"
    35 = "District 5"
    36 = "District 6"
    37 = "District 7"
    38 = "District 8"
    39 = "District 9"
    40 = "District 10"
    41 = "District 11"
    42 = "District 12"
    43 = "District 13"
    44 = "District 14"
    45 = "District 15"
    46 = "District 16"
    47 = "District 17"
    48 = "District 18"
    49 = "District 19"
    50 = "District 20"
    51 = "District 21"
    52 = "District 22"
    53 = "District 23"
    54 = "District 24"
    55 = "District 25"
    56 = "District 26"
    57 = "District 27"
    58 = "District 28"
    59 = "District 29"
    60 = "District 30"
    61 = "District 31"
    62 = "District 32"
    63 = "District 33"
    64 = "District 34"
    65 = "District 35"
    66 = "District 36"
    67 = "District 37"
    68 = "District 38"
    69 = "District 39"
    70 = "District 40"
    71 = "Election 1 Vote Method"  # See Election Map documentation for Election 1 to Election 40. AP=At Polls AB=Absentee MB = Mail_In Ballot P=Provisional
    72 = "Election 1 Party"  # See Political Party Code
    73 = "Election 2 Vote Method"
    74 = "Election 2 Party"
    75 = "Election 3 Vote Method"
    76 = "Election 3 Party"
    77 = "Election 4 Vote Method"
    78 = "Election 4 Party"
    79 = "Election 5 Vote Method"
    80 = "Election 5 Party"
    81 = "Election 6 Vote Method"
    82 = "Election 6 Party"
    83 = "Election 7 Vote Method"
    84 = "Election 7 Party"
    85 = "Election 8 Vote Method"
    86 = "Election 8 Party"
    87 = "Election 9 Vote Method"
    88 = "Election 9 Party"
    89 = "Election 10 Vote Method"
    90 = "Election 10 Party"
    91 = "Election 11 Vote Method"
    92 = "Election 11 Party"
    93 = "Election 12 Vote Method"
    94 = "Election 12 Party"
    95 = "Election 13 Vote Method"
    96 = "Election 13 Party"
    97 = "Election 14 Vote Method"
    98 = "Election 14 Party"
    99 = "Election 15 Vote Method"
    100 = "Election 15 Party"
    101 = "Election 16 Vote Method"
    102 = "Election 16 Party"
    103 = "Election 17 Vote Method"
    104 = "Election 17 Party"
    105 = "Election 18 Vote Method"
    106 = "Election 18 Party"
    107 = "Election 19 Vote Method"
    108 = "Election 19 Party"
    109 = "Election 20 Vote Method"
    110 = "Election 20 Party"
    111 = "Election 21 Vote Method"
    112 = "Election 21 Party"
    113 = "Election 22 Vote Method"
    114 = "Election 22 Party"
    115 = "Election 23 Vote Method"
    116 = "Election 23 Party"
    117 = "Election 24 Vote Method"
    118 = "Election 24 Party"
    119 = "Election 25 Vote Method"
    120 = "Election 25 Party"
    121 = "Election 26 Vote Method"
    122 = "Election 26 Party"
    123 = "Election 27 Vote Method"
    124 = "Election 27 Party"
    125 = "Election 28 Vote Method"
    126 = "Election 28 Party"
    127 = "Election 29 Vote Method"
    128 = "Election 29 Party"
    129 = "Election 30 Vote Method"
    130 = "Election 30 Party"
    131 = "Election 31 Vote Method"
    132 = "Election 31 Party"
    133 = "Election 32 Vote Method"
    134 = "Election 32 Party"
    135 = "Election 33 Vote Method"
    136 = "Election 33 Party"
    137 = "Election 34 Vote Method"
    138 = "Election 34 Party"
    139 = "Election 35 Vote Method"
    140 = "Election 35 Party"
    141 = "Election 36 Vote Method"
    142 = "Election 36 Party"
    143 = "Election 37 Vote Method"
    144 = "Election 37 Party"
    145 = "Election 38 Vote Method"
    146 = "Election 38 Party"
    147 = "Election 39 Vote Method"
    148 = "Election 39 Party"
    149 = "Election 40 Vote Method"
    150 = "Election 40 Party"
    151 = "Home Phone"
    152 = "County Name"  # County Name
    153 = "Mail Country"


# FIELD RENAMING DECLARATIONS

[FIELDS]
voter_vuid = "ID NUMBER"
voter_registration_date = "REGISTRATION DATE"
voter_registration_status = "VOTER STATUS"
voter_registration_status_reason = 'null'
voter_political_party = "PARTY CODE"
voter_precinct_number = "PRECINCT CODE"

# PERSON NAME FIELDS
person_name_first = "FIRST NAME"
person_name_middle = "MIDDLE NAME"
person_name_last = "LAST NAME"
person_name_suffix = "SUFFIX"
person_dob = "DOB"
person_gender = "GENDER"

# RESIDENTIAL ADDRESS FIELDS
residence_address1 = "RADDRESS1"
residence_address2 = "ADDRESS LINE 2 RESIDENTIAL"
residence_city = "CITY RESIDENTIAL"
residence_state = "STATE RESIDENTIAL"
residence_zip5 = "ZIP RESIDENTIAL"

# RESIDENTIAL ADDRESS FIELD PARTS
residence_part_number = "HOUSE NUMBER RESIDENTIAL"
residence_part_number_suffix = "HOUSE NUMBER SUFFIX RESIDENTIAL"
residence_part_street_name = "STREET NAME RESIDENTIAL"
residence_part_unit_number = "APARTMENT NUMBER RESIDENTIAL"
residence_part_city = "CITY RESIDENTIAL"
residence_part_state = "STATE RESIDENTIAL"
residence_part_zip5 = "ZIP RESIDENTIAL"


# MAILING ADDRESS FIELDS
mail_address1 = "MAIL ADDRESS 1"
mail_address2 = "MAIL ADDRESS 2"
mail_city = "MAIL CITY"
mail_state = "MAIL STATE"
mail_zip5 = "MAIL ZIP"
mail_zip4 = "null"

# DISTRICTS: CITY
district_city_name = "CITY"
district_city_chool_district = "SCHOOLDIST"
district_county_id = "COUNTY NAME"
district_county_township = "TOWNSHIP"