from app.conf.tec_postgres import Base
from sqlalchemy import Column, Integer, String, Float, Boolean, Date, DateTime, JSON


class TECContributionRecord(Base):
    __tablename__ = "tec_contributions"
    __table_args__ = {'schema': 'texas'}

    recordType = Column(String, nullable=False)
    formTypeCd = Column(String, nullable=False)
    schedFormTypeCd = Column(String, nullable=False)
    reportInfoIdent = Column(Integer, nullable=False)
    receivedDt = Column(DateTime, nullable=False)
    infoOnlyFlag = Column(String, nullable=True)
    filerIdent = Column(Integer, nullable=False)
    filerTypeCd = Column(String, nullable=False)
    filerName = Column(String, nullable=False)
    filerNameFormatted = Column(String, nullable=True)
    filerFirstName = Column(String, nullable=True)
    filerLastName = Column(String, nullable=True)
    filerMiddleName = Column(String, nullable=True)
    filerPrefix = Column(String, nullable=True)
    filerSuffix = Column(String, nullable=True)
    filerCompanyName = Column(String, nullable=True)
    filerCompanyNameFormatted = Column(String, nullable=True)
    contributionInfoId = Column(Integer, nullable=True)
    contributionDt = Column(DateTime, nullable=False)
    contributionAmount = Column(Float, nullable=True)
    contributionDescr = Column(String, nullable=True)
    itemizeFlag = Column(String, nullable=True)
    travelFlag = Column(String, nullable=True)
    contributorPersentTypeCd = Column(String, nullable=True)
    contributorNameOrganization = Column(String, nullable=True)
    contributorNameLast = Column(String, nullable=True)
    contributorNameSuffixCd = Column(String, nullable=True)
    contributorNameFirst = Column(String, nullable=True)
    contributorNamePrefixCd = Column(String, nullable=True)
    contributorNameShort = Column(String, nullable=True)
    contributorStreetCity = Column(String, nullable=True)
    contributorStreetStateCd = Column(String, nullable=True)
    contributorStreetCountyCd = Column(String, nullable=True)
    contributorStreetCountryCd = Column(String, nullable=True)
    contributorStreetPostalCode = Column(String, nullable=True)
    contributorZipCode5 = Column(Integer, nullable=True)
    contributorZipCode4 = Column(Integer, nullable=True)
    contributorStreetRegion = Column(String, nullable=True)
    contributorEmployer = Column(String, nullable=True)
    contributorOccupation = Column(String, nullable=True)
    contributorJobTitle = Column(String, nullable=True)
    contributorPacFein = Column(String, nullable=True)
    contributorOosPacFlag = Column(String, nullable=True)
    contributorLawFirmName = Column(String, nullable=True)
    contributorSpouseLawFirmName = Column(String, nullable=True)
    contributorParent1LawFirmName = Column(String, nullable=True)
    contributorParent2LawFirmName = Column(String, nullable=True)
    AbstractRecordErrors = Column(JSON, nullable=True)
    AbstractRecordUUID = Column(String, primary_key=True, nullable=False)
    AbstractRecordUpdateDt = Column(DateTime, nullable=False)
