from app.conf.tec_postgres import Base
from sqlalchemy import Column, Integer, String, Float, Boolean, Date, DateTime


class TECRecord(Base):
    __tablename__ = "tec_records"
    __table_args__ = {'schema': 'texas'}

    recordType = Column(String, nullable=True)
    formTypeCd = Column(String, nullable=True)
    schedFormTypeCd = Column(String, nullable=True)
    reportInfoIdent = Column(Integer, nullable=True)
    receivedDt = Column(Date, nullable=False)
    infoOnlyFlag = Column(Boolean, nullable=True)
    filerIdent = Column(Integer, nullable=True)
    filerTypeCd = Column(String, nullable=True)
    filerTitle = Column(String, nullable=True)
    filerName = Column(String, nullable=True)
    filerNameFormatted = Column(String, nullable=True)
    filerFirstName = Column(String, nullable=True)
    filerLastName = Column(String, nullable=True)
    filerMiddleName = Column(String, nullable=True)
    filerPrefix = Column(String, nullable=True)
    filerSuffix = Column(String, nullable=True)
    filerCompanyName = Column(String, nullable=True)
    filerCompanyNameFormatted = Column(String, nullable=True)
    expendInfoId = Column(Integer, nullable=True)
    expendDt = Column(Date, nullable=True)
    expendAmount = Column(Float, nullable=True)
    expendDescr = Column(String, nullable=True)
    expendCatCd = Column(String, nullable=True)
    expendCatDescr = Column(String, nullable=True)
    itemizeFlag = Column(Boolean, nullable=True)
    travelFlag = Column(Boolean, nullable=True)
    politicalExpendCd = Column(Boolean, nullable=True)
    reimburseIntendedFlag = Column(Boolean, nullable=True)
    srcCorpContribFlag = Column(Boolean, nullable=True)
    capitalLivingexpFlag = Column(String, nullable=True)
    payeePersentTypeCd = Column(String, nullable=True)
    payeeNameOrganization = Column(String, nullable=True)
    payeeCompanyName = Column(String, nullable=True)
    payeeCompanyNameFormatted = Column(String, nullable=True)
    payeeNameLast = Column(String, nullable=True)
    payeeNameSuffixCd = Column(String, nullable=True)
    payeeNameFirst = Column(String, nullable=True)
    payeeNamePrefixCd = Column(String, nullable=True)
    payeeNameShort = Column(String, nullable=True)
    payeeStreetAddr1 = Column(String, nullable=True)
    payeeStreetAddr2 = Column(String, nullable=True)
    payeeStreetCity = Column(String, nullable=True)
    payeeStreetStateCd = Column(String, nullable=True)
    payeeStreetCountyCd = Column(String, nullable=True)
    payeeStreetCountryCd = Column(String, nullable=True)
    payeeStreetPostalCode = Column(String, nullable=True)
    payeeStreetPostalCode4 = Column(String, nullable=True)
    payeeStreetRegion = Column(String, nullable=True)
    creditCardIssuer = Column(String, nullable=True)
    repaymentDt = Column(Date, nullable=True)
    contributionInfoId = Column(Integer, nullable=True)
    contributionDt = Column(Date, nullable=True)
    contributionAmount = Column(Float, nullable=True)
    contributionDescr = Column(String, nullable=True)
    contributionCatCd = Column(String, nullable=True)
    contributorNameOrganization = Column(String, nullable=True)
    contributorNameLast = Column(String, nullable=True)
    contributorNameSuffixCd = Column(String, nullable=True)
    contributorNameFirst = Column(String, nullable=True)
    contributorNamePrefixCd = Column(String, nullable=True)
    contributorNameShort = Column(String, nullable=True)
    contributorStreetCity = Column(String, nullable=True)
    contributorStreetStateCd = Column(String, nullable=True)
    contributorStreetCountyCd = Column(String, nullable=True)
    contributorStreetCountryCd = Column(String, nullable=True)
    contributorStreetPostalCode = Column(String, nullable=True)
    contributorStreetPostalCode4 = Column(String, nullable=True)
    contributorStreetRegion = Column(String, nullable=True)
    contributorEmployer = Column(String, nullable=True)
    contributorOccupation = Column(String, nullable=True)
    contributorJobTitle = Column(String, nullable=True)
    contributorPacFein = Column(String, nullable=True)
    contributorOosPacFlag = Column(Boolean, nullable=True)
    contributorLawFirmName = Column(String, nullable=True)
    contributorSpouseLawFirmName = Column(String, nullable=True)
    contributorParent1LawFirmName = Column(String, nullable=True)
    contributorParent2LawFirmName = Column(String, nullable=True)
    # AbstractContributionHash = Column(String, nullable=True)
    # AbstractExpenseHash = Column(String, nullable=True)
    AbstractRecordUUID = Column(String, nullable=False, primary_key=True)
    AbstractRecordUpdateDt = Column(DateTime, nullable=False)
