from app.conf.tec_postgres import Base
from sqlalchemy import Column, Integer, String, Float, Boolean, Date, DateTime, JSON



class TECExpenseRecord(Base):
    __tablename__ = "tec_expenses"
    __table_args__ = {'schema': 'texas'}

    recordType = Column(String, nullable=False)
    formTypeCd = Column(String, nullable=False)
    schedFormTypeCd = Column(String, nullable=False)
    reportInfoIdent = Column(Integer, nullable=False)
    receivedDt = Column(Date, nullable=False)
    infoOnlyFlag = Column(String, nullable=True)
    filerIdent = Column(Integer, nullable=False)
    filerTypeCd = Column(String, nullable=True)
    filerName = Column(String, nullable=False)
    filerNameFormatted = Column(String, nullable=True)
    filerFirstName = Column(String, nullable=True)
    filerLastName = Column(String, nullable=True)
    filerMiddleName = Column(String, nullable=True)
    filerPrefix = Column(String, nullable=True)
    filerSuffix = Column(String, nullable=True)
    filerCompanyName = Column(String, nullable=True)
    filerCompanyNameFormatted = Column(String, nullable=True)
    expendInfoId = Column(Integer, nullable=True)
    expendDt = Column(Date, nullable=False)
    expendAmount = Column(Float, nullable=False)
    expendDescr = Column(String, nullable=True)
    expendCatCd = Column(String, nullable=True)
    expendCatDescr = Column(String, nullable=True)
    itemizeFlag = Column(String, nullable=True)
    travelFlag = Column(String, nullable=True)
    politicalExpendCd = Column(String, nullable=True)
    reimburseIntendedFlag = Column(String, nullable=True)
    srcCorpContribFlag = Column(String, nullable=True)
    capitalLivingexpFlag = Column(String, nullable=True)
    payeePersentTypeCd = Column(String, nullable=True)
    payeeNameOrganization = Column(String, nullable=True)
    payeeNameLast = Column(String, nullable=True)
    payeeNameSuffixCd = Column(String, nullable=True)
    payeeNameFirst = Column(String, nullable=True)
    payeeNamePrefixCd = Column(String, nullable=True)
    payeeNameShort = Column(String, nullable=True)
    payeeStreetAddr1 = Column(String, nullable=False)
    payeeStreetAddr2 = Column(String, nullable=True)
    payeeStreetCity = Column(String, nullable=False)
    payeeStreetStateCd = Column(String, nullable=True)
    payeeStreetCountyCd = Column(String, nullable=True)
    payeeStreetCountryCd = Column(String, nullable=True)
    payeeStreetPostalCode = Column(String, nullable=True)
    payeeZipCode5 = Column(Integer, nullable=True)
    payeeZipCode4 = Column(Integer, nullable=True)
    payeeStreetRegion = Column(String, nullable=True)
    creditCardIssuer = Column(String, nullable=True)
    repaymentDt = Column(Date, nullable=True)
    AbstractRecordErrors = Column(JSON, nullable=True)
    AbstractRecordUUID = Column(String, nullable=False, primary_key=True)
    AbstractRecordUpdateDt = Column(DateTime, nullable=False)
